// <auto-generated />
using System;
using AxaColpatria.NotAxApp.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AxaColpatria.NotAxApp.Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917154417_AddRelationsUsuarioTableroNota")]
    partial class AddRelationsUsuarioTableroNota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TableroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TableroId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Tablero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tableros");
                });

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Nota", b =>
                {
                    b.HasOne("AxaColpatria.NotAxApp.Core.Models.Tablero", "Tablero")
                        .WithMany("Notas")
                        .HasForeignKey("TableroId");

                    b.Navigation("Tablero");
                });

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Tablero", b =>
                {
                    b.HasOne("AxaColpatria.NotAxApp.Core.Models.Usuario", "Usuario")
                        .WithMany("Tableros")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Tablero", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("AxaColpatria.NotAxApp.Core.Models.Usuario", b =>
                {
                    b.Navigation("Tableros");
                });
#pragma warning restore 612, 618
        }
    }
}
